apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: HOLA_MUNDO
      value: "hola mundo"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    resources:
      requests:
        memory: "4Mi"
        cpu: "20m"
      limits:
        memory: "8Mi"
        cpu: "50m"
    readinessProbe:
        path: /
        port: 90
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 90
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 90  


                